### ISSUE TITLE
Project description - Main link is dead

### ISSUE THREAD

**Issue by senpl** [GuildCrafts/web-development-js#448]
Main link used in description is not working http://jsdev.learnersguild.org/ it gives 
This site can’t be reached
jsdev.learnersguild.org’s server IP address could not be found.
Search Google for jsdev learners guild org
ERR_NAME_NOT_RESOLVED
 label: `bug`

**Comment by jrpool** [comment]
This organization has terminated its operations. It has likely retired all of its subdomains except www.
